name: 🐞 Bug report
description: Report a bug in Micrometer
labels: [bug]

body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: input
    attributes:
      label: Micrometer version
      description: What version of Micrometer is affected by the bug? Before submitting a bug report, please try with the latest patch version available in the [supported minor version](https://micrometer.io/docs/support) you are using.
      placeholder: 1.7.3
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Micrometer module
      description: Which module is the bug related to?
      options:
        - micrometer-core
        - micrometer-bom
        - micrometer-jersey2
        - micrometer-registry-appoptics
        - micrometer-registry-atlas
        - micrometer-registry-azure-monitor
        - micrometer-registry-cloudwatch
        - micrometer-registry-cloudwatch2
        - micrometer-registry-datadog
        - micrometer-registry-dynatrace
        - micrometer-registry-elastic
        - micrometer-registry-ganglia
        - micrometer-registry-graphite
        - micrometer-registry-health
        - micrometer-registry-humio
        - micrometer-registry-influx
        - micrometer-registry-jmx
        - micrometer-registry-kairos
        - micrometer-registry-new-relic
        - micrometer-registry-opentsdb
        - micrometer-registry-prometheus
        - micrometer-registry-signalfx
        - micrometer-registry-stackdriver
        - micrometer-registry-statsd
        - micrometer-registry-wavefront
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Operating system
      description: On which operating systems is the issue reproducible?
      options:
        - label: Linux
        - label: macOS
        - label: Windows
  - type: textarea
    attributes:
      label: Java version
      description: What version of Java is used to run the application with the bug? Ideally provide the output of the `java -version` command.
      placeholder: |
        openjdk version "16.0.1" 2021-04-20
        OpenJDK Runtime Environment (build 16.0.1+9)
        OpenJDK 64-Bit Server VM (build 16.0.1+9, mixed mode, sharing)
      render: code
    validations:
      required: true
  - type: textarea
    attributes:
      label: Issue reproduction instructions
      description: |
        How can the unexpected behavior be reproduced? What is the expected behavior?
        Ideally provide unit test code or a link to a public source code repository with a minimal sample project that can be run to reproduce.
        Without a reliable way to reproduce the issue, it is hard to reliably fix or understand the root cause.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      description: Provide any other context related to the issue such as similar issues in this repository or others.
    validations:
      required: false
